[project]
name = "niripy"
version = "0.2.4"
authors = [
  { name = "Kevin McNamara", email = "kevin.j.mcnamara+tech@proton.me" },
]
description = "Python bindings for Niri."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = ["pydantic>=2.12.5"]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Desktop Environment :: Window Managers",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/kjmcnamara1/niripy"
Issues = "https://github.com/kjmcnamara1/niripy/issues"

[build-system]
requires = ["uv_build>=0.9.22,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["icecream>=2.1.9", "pyright>=1.1.408"]
test = ["pytest-cov>=7.0.0", "vermin>=1.8.0"]

[tool.basedpyright]
reportAny = "none"
reportExplicitAny = "none"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
